In [1]:
import numpy as np

## Create Arrays

In [2]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [5]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 4, 0],
       [9, 1, 6],
       [3, 9, 5]])

In [8]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Specify data type of array elements when constructing
np.zeros(5, dtype='float64')

array([0., 0., 0., 0., 0.])

## Numpy Array Attributes

In [10]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

Each array has attributes

- `ndim` : the number of dimensions

- `shape` : the size of each dimension

- `size` : the total size of the array

- `dtype`: data type of the array

-  `itemsize`: the size (in bytes) of each array element

- `nbytes`: the total size (in bytes) of the array (= `itemsize` * `size`)

In [11]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [12]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
itemsize: 8 bytes
nbytes: 480 bytes


## Array Indexing

In [13]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
x2[2, 0]

1

In [15]:
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [16]:
x2.copy()[0, 0] = 12
x2.copy()

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

Keep in mind that, unlike Python lists, **NumPy arrays have a fixed type**. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated!!!

## Array Slicing: Accessing Subarrays

Syntax: `x[start:stop:step]`

- If any of these are unspecified, they default to the values `start=0`, `stop=`*`size of dimension`*, `step=1`. 

- If `step` value is **negative**, that means **reverse** slicing

### One-dimensional subarrays

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [19]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensional subarrays

In [20]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [21]:
x2[:2, :3] # row 0 and 1, column 0, 1, 2 (two rows, three columns)

array([[3, 5, 2],
       [7, 6, 8]])

In [22]:
x2[:, ::2] # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [23]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

#### Accessing rows and columns

In [24]:
x2[:, 0] # first column of x2

array([3, 7, 1])

In [25]:
x2[0, :] # first row of x2

array([3, 5, 2, 4])

For row access we can use a more compact syntax:

In [26]:
x2[0]

array([3, 5, 2, 4])

### Subarrays as no-copy views

Numpy array slices return *views* rather than *copies* of the array data

In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [28]:
x2_sub = x2[:2, :2]
x2_sub

array([[3, 5],
       [7, 6]])

If we modify this subarray, we'll see that the original array is changed!

In [29]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [30]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Reshaping of Arrays

The size of the initial array must match the size of the reshaped array. 

In [31]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`newaxis`: increase the dimension of the existing array by one more dimension

E.g., Conversion of a one-dimensional array into a two-dimensional row or column matrix.

In [32]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [33]:
# row vector via reshape
print(x.reshape((1, 3)))
print(x.reshape((1, 3)).shape)

[[1 2 3]]
(1, 3)


In [34]:
# row vector via newaxis
print(x[np.newaxis, :])
print(x[np.newaxis, :].shape)

[[1 2 3]]
(1, 3)


In [35]:
# column vector via reshape
print(x.reshape((3, 1)))
print(x.reshape((3, 1)).shape)

[[1]
 [2]
 [3]]
(3, 1)


In [36]:
# column vector via newaxis
print(x[:, np.newaxis])
print(x[:, np.newaxis].shape)

[[1]
 [2]
 [3]]
(3, 1)


## Array Concatenation and Splitting

### Concatenation

In [37]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]

In [38]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [39]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [40]:
# concatenate along the first axis (down)
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, use the `np.vstack` (vertical stack) and `np.hstack` (horizontal stack) functions:

In [42]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [43]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [44]:
y = np.array([[99],
              [99]])

# horizontally stack the arrays
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [45]:
np.hstack([y, grid])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

`np.dstack` (depth stack) will stack array along the third axis.

In [46]:
a = np.array((1, 2, 3))
b = np.array((2, 3, 4))

In [47]:
a

array([1, 2, 3])

In [48]:
b

array([2, 3, 4])

In [49]:
x4 = np.random.randint(10, size=(2, 3, 4))
x4

array([[[4, 3, 4, 4],
        [8, 4, 3, 7],
        [5, 5, 0, 1]],

       [[5, 9, 3, 0],
        [5, 0, 1, 2],
        [4, 2, 0, 3]]])

In [50]:
x5 = np.random.randint(20, size=(2, 3, 4))
x5

array([[[ 2, 10, 13, 16],
        [ 7,  9,  0, 10],
        [18, 11,  2,  2]],

       [[ 3,  3, 18, 14],
        [ 3, 17, 18, 14],
        [ 9,  1,  4, 10]]])

In [51]:
np.hstack([x4, x5])

array([[[ 4,  3,  4,  4],
        [ 8,  4,  3,  7],
        [ 5,  5,  0,  1],
        [ 2, 10, 13, 16],
        [ 7,  9,  0, 10],
        [18, 11,  2,  2]],

       [[ 5,  9,  3,  0],
        [ 5,  0,  1,  2],
        [ 4,  2,  0,  3],
        [ 3,  3, 18, 14],
        [ 3, 17, 18, 14],
        [ 9,  1,  4, 10]]])

In [52]:
np.vstack([x4, x5])

array([[[ 4,  3,  4,  4],
        [ 8,  4,  3,  7],
        [ 5,  5,  0,  1]],

       [[ 5,  9,  3,  0],
        [ 5,  0,  1,  2],
        [ 4,  2,  0,  3]],

       [[ 2, 10, 13, 16],
        [ 7,  9,  0, 10],
        [18, 11,  2,  2]],

       [[ 3,  3, 18, 14],
        [ 3, 17, 18, 14],
        [ 9,  1,  4, 10]]])

In [53]:
np.dstack([x4, x5])

array([[[ 4,  3,  4,  4,  2, 10, 13, 16],
        [ 8,  4,  3,  7,  7,  9,  0, 10],
        [ 5,  5,  0,  1, 18, 11,  2,  2]],

       [[ 5,  9,  3,  0,  3,  3, 18, 14],
        [ 5,  0,  1,  2,  3, 17, 18, 14],
        [ 4,  2,  0,  3,  9,  1,  4, 10]]])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions `np.split`, `np.hsplit`, and `np.vsplit`. 

For each of these, we can pass a list of indices giving the split points:

In [54]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [55]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
upper, lower = np.vsplit(grid, [2])

print("upper:\n", upper)
print("lower:\n", lower)

upper:
 [[0 1 2 3]
 [4 5 6 7]]
lower:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [57]:
left, right = np.hsplit(grid, [2])

print("left:\n", left)
print("right:\n", right)

left:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
