## 1-D arrays work differently!!!

In a 1-d Numpy array, the first and only axis is axis 0!

In [8]:
import numpy as np

In [9]:
l1 = np.array([1,1,1])
l2 = np.array([9,9,9])

In [10]:
print(l1)
print(l1.shape)

[1 1 1]
(3,)


In [11]:
print(l2)
print(l2.shape)

[9 9 9]
(3,)


In [12]:
np.concatenate([l1, l2], axis=0)

array([1, 1, 1, 9, 9, 9])

In [13]:
np.concatenate([l1, l2], axis=1) # Error, since there's only axis 0

AxisError: axis 1 is out of bounds for array of dimension 1