In [1]:
import numpy as np

In [2]:
x1 = np.array([[[9, 3, 7, 3],
        [2, 1, 1, 2],
        [1, 4, 2, 5]],

       [[5, 5, 2, 5],
        [7, 7, 6, 1],
        [6, 7, 2, 3]]])

In [3]:
x1

array([[[9, 3, 7, 3],
        [2, 1, 1, 2],
        [1, 4, 2, 5]],

       [[5, 5, 2, 5],
        [7, 7, 6, 1],
        [6, 7, 2, 3]]])

In [11]:
x2 = np.random.randint(20, size=(2, 3, 4))
x2

array([[[16, 13, 19, 16],
        [15, 19,  1,  2],
        [ 4, 15,  5,  7]],

       [[18, 18,  1,  9],
        [ 5, 19,  7, 11],
        [ 8, 10,  2, 18]]])

In [20]:
np.hstack((x1, x2)) # horizontally stack, equivalent to concatenate along column

array([[[ 9,  3,  7,  3],
        [ 2,  1,  1,  2],
        [ 1,  4,  2,  5],
        [16, 13, 19, 16],
        [15, 19,  1,  2],
        [ 4, 15,  5,  7]],

       [[ 5,  5,  2,  5],
        [ 7,  7,  6,  1],
        [ 6,  7,  2,  3],
        [18, 18,  1,  9],
        [ 5, 19,  7, 11],
        [ 8, 10,  2, 18]]])

In [21]:
np.concatenate([x1, x2], axis=1) # concatenate along column

array([[[ 9,  3,  7,  3],
        [ 2,  1,  1,  2],
        [ 1,  4,  2,  5],
        [16, 13, 19, 16],
        [15, 19,  1,  2],
        [ 4, 15,  5,  7]],

       [[ 5,  5,  2,  5],
        [ 7,  7,  6,  1],
        [ 6,  7,  2,  3],
        [18, 18,  1,  9],
        [ 5, 19,  7, 11],
        [ 8, 10,  2, 18]]])

In [22]:
np.vstack([x1, x2]) # vertically stack, equivalent to concatenate along row

array([[[ 9,  3,  7,  3],
        [ 2,  1,  1,  2],
        [ 1,  4,  2,  5]],

       [[ 5,  5,  2,  5],
        [ 7,  7,  6,  1],
        [ 6,  7,  2,  3]],

       [[16, 13, 19, 16],
        [15, 19,  1,  2],
        [ 4, 15,  5,  7]],

       [[18, 18,  1,  9],
        [ 5, 19,  7, 11],
        [ 8, 10,  2, 18]]])

In [23]:
np.concatenate([x1, x2], axis=0) # concatenate along row

array([[[ 9,  3,  7,  3],
        [ 2,  1,  1,  2],
        [ 1,  4,  2,  5]],

       [[ 5,  5,  2,  5],
        [ 7,  7,  6,  1],
        [ 6,  7,  2,  3]],

       [[16, 13, 19, 16],
        [15, 19,  1,  2],
        [ 4, 15,  5,  7]],

       [[18, 18,  1,  9],
        [ 5, 19,  7, 11],
        [ 8, 10,  2, 18]]])

In [17]:
np.vstack([x1, x2]).shape 

(4, 3, 4)

In [18]:
np.dstack([x1, x2]) # depth-wise stack, equivalent to concatenate along the third axis (depth)

array([[[ 9,  3,  7,  3, 16, 13, 19, 16],
        [ 2,  1,  1,  2, 15, 19,  1,  2],
        [ 1,  4,  2,  5,  4, 15,  5,  7]],

       [[ 5,  5,  2,  5, 18, 18,  1,  9],
        [ 7,  7,  6,  1,  5, 19,  7, 11],
        [ 6,  7,  2,  3,  8, 10,  2, 18]]])

In [24]:
np.concatenate([x1, x2], axis=2) # concatenate along the third axis

array([[[ 9,  3,  7,  3, 16, 13, 19, 16],
        [ 2,  1,  1,  2, 15, 19,  1,  2],
        [ 1,  4,  2,  5,  4, 15,  5,  7]],

       [[ 5,  5,  2,  5, 18, 18,  1,  9],
        [ 7,  7,  6,  1,  5, 19,  7, 11],
        [ 6,  7,  2,  3,  8, 10,  2, 18]]])