## Computation: Universal Functions

*Vectorized* operation: simply performing an operation on the array, which will then be applied to each element.

Below are some common Ufunc:

### Array arithmetic

| Operator | Equivalent ufunc  | Description                           |
| :------- | :---------------- | :------------------------------------ |
| `+`      | `np.add`          | Addition (e.g., `1 + 1 = 2`)          |
| `-`      | `np.subtract`     | Subtraction (e.g., `3 - 2 = 1`)       |
| `-`      | `np.negative`     | Unary negation (e.g., `-2`)           |
| `*`      | `np.multiply`     | Multiplication (e.g., `2 * 3 = 6`)    |
| `/`      | `np.divide`       | Division (e.g., `3 / 2 = 1.5`)        |
| `//`     | `np.floor_divide` | Floor division (e.g., `3 // 2 = 1`)   |
| `**`     | `np.power`        | Exponentiation (e.g., `2 ** 3 = 8`)   |
| `%`      | `np.mod`          | Modulus/remainder (e.g., `9 % 4 = 1`) |

### Absolute value

In [60]:
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [63]:
x_complex = np.array([3 - 4j, 3 - 4j, 2 + 0j, 0 + 1j])
np.abs(x_complex)

array([5., 5., 2., 1.])

### Trigonometric & Inverse trigonometric functions

In [64]:
theta = np.linspace(0, np.pi, 3)

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


### Exponents and logarithms

In [65]:
x = [1, 2, 3]

print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [66]:
x = [1, 2, 4, 10]

print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


Some specialized versions that are useful for maintaining precision with very small input:

In [67]:
x = [0, 0.001, 0.01, 0.1]

print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


When `x` is very small, these functions give more precise values than if the raw `np.log` or `np.exp` were to be used.

## Specify Output

In [11]:
x = np.arange(5)
y = np.empty(5)
z = np.zeros(10)

In [7]:
y

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [8]:
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40.])

In [9]:
y

array([ 0., 10., 20., 30., 40.])

In [12]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.power(2, x, out=z[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [15]:
z

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

## Aggregates

`reduce`: repeatedly applies a given operation to the elements of an array until only a single result remains.

In [16]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [17]:
np.add.reduce(x)

15

In [18]:
np.multiply.reduce(x)

120

`accumulate`: Store the intermediate results of the computation

In [19]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [20]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])